'use strict';

/* =========================================================
   CONFIGURACIÓN INTERNA
   Para personalizar un cliente, edita únicamente js/cliente.js
========================================================= */

const CONFIG = {
  CATALOGO_ID: CLIENTE.CATALOGO_ID, 
  STORE_NAME: CLIENTE.NOMBRE,
  STORE_DESCRIPTION: CLIENTE.DESCRIPCION,
  SITE_URL: CLIENTE.URL_WEB,
  LOGO_URL: CLIENTE.LOGO,
  LOGO_SOCIAL: CLIENTE.COMPARTIR?.IMAGEN || CLIENTE.LOGO,
  SHARE_TITLE: CLIENTE.COMPARTIR?.TITULO || CLIENTE.NOMBRE,
  SHARE_DESCRIPTION: CLIENTE.COMPARTIR?.DESCRIPCION || CLIENTE.DESCRIPCION,
  DEFAULT_ANNOUNCEMENT: CLIENTE.ANUNCIOS || {},
  GOOGLE_SHEET_ID: CLIENTE.GOOGLE_SHEET_ID,

  SHEETS: {
    CONFIG: "CONFIG",
    PRODUCTOS: "PRODUCTOS",
    VARIANTES: "VARIANTES",
    COLORES: "COLORES",
    MAYOREO: "MAYOREO",
    INFORMACION: "INFORMACION"
  },

  INITIAL_PRODUCTS: Number(CLIENTE.PRODUCTOS_INICIALES) || 24,
  LOAD_MORE_PRODUCTS: Number(CLIENTE.PRODUCTOS_POR_CARGA) || 24,
  CACHE_MINUTES: Number(CLIENTE.CACHE_MINUTOS) || 5,
  CACHE_VERSION: Number(CLIENTE.CACHE_VERSION) || 1,

  CURRENCY: CLIENTE.MONEDA || "S/",
  DECIMALS: Number.isFinite(Number(CLIENTE.DECIMALES)) ? Number(CLIENTE.DECIMALES) : 2,
  CREATED_BY: CLIENTE.CREADO_POR || "",
  PLACEHOLDER_IMAGE: CLIENTE.IMAGEN_POR_DEFECTO || "assets/placeholder.webp"
};

CONFIG.getSheetUrl = function(sheetName){
  if(!CONFIG.GOOGLE_SHEET_ID){
    console.warn("Falta GOOGLE_SHEET_ID en js/cliente.js");
    return "";
  }
  return `https://docs.google.com/spreadsheets/d/${CONFIG.GOOGLE_SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheetName)}`;
};

CONFIG.URLS = {
  CONFIG: CONFIG.getSheetUrl(CONFIG.SHEETS.CONFIG),
  PRODUCTOS: CONFIG.getSheetUrl(CONFIG.SHEETS.PRODUCTOS),
  VARIANTES: CONFIG.getSheetUrl(CONFIG.SHEETS.VARIANTES),
  COLORES: CONFIG.getSheetUrl(CONFIG.SHEETS.COLORES),
  MAYOREO: CONFIG.getSheetUrl(CONFIG.SHEETS.MAYOREO),
  INFORMACION: CONFIG.getSheetUrl(CONFIG.SHEETS.INFORMACION)
};
